name: Build & Artifact (.NET)

on:
  push:
    branches: [ "eature/dotnet" ]
  pull_request:
    branches: [ "eature/dotnet" ]
 # workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      PROJECT_PATH: be/WebAPI/Alumni.WebAPI.csproj   # <-- change this
      ARTIFACT_NAME: myapp_publish
      PUBLISH_DIR: ${{ github.workspace }}\publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" -c ${{ env.CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c ${{ env.CONFIGURATION }} --no-build -o "${{ env.PUBLISH_DIR }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
          retention-days: 14
